DROP TABLE IF EXISTS catalog_rel;
DROP TABLE IF EXISTS catalog_node;

CREATE TABLE catalog_node (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT DEFAULT 0 NOT NULL,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(50),
    path VARCHAR(500),
    level INT,
    sort INT
);

CREATE INDEX idx_catalog_node_parent_sort_id ON catalog_node(parent_id, sort, id);
CREATE INDEX idx_catalog_node_path ON catalog_node(path);

CREATE TABLE catalog_rel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id BIGINT NOT NULL,
    biz_id VARCHAR(100) NOT NULL,
    biz_type VARCHAR(50) NOT NULL,
    CONSTRAINT uk_catalog_rel_biz UNIQUE (biz_id, biz_type)
);

CREATE INDEX idx_catalog_rel_node_type ON catalog_rel(node_id, biz_type);
