DROP TABLE IF EXISTS catalog_rel;
DROP TABLE IF EXISTS catalog_node;

CREATE TABLE catalog_node (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT DEFAULT 0 NOT NULL,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(50),
    path VARCHAR(500),
    level INT,
    sort INT
);

CREATE INDEX idx_catalog_node_parent ON catalog_node(parent_id);
CREATE INDEX idx_catalog_node_path ON catalog_node(path);
