server:
  port: 8080

spring:
  profiles:
    default: local

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

catalog:
  enabled: true
  enable-rest-api: true
