name: Maven Package

on:
  push:
    tags:
      - '*'  # 当推送标签时触发发布

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # 使用与项目匹配的 JDK 版本
          distribution: 'adopt'
          server-id: github
          server-username: GITHUB_USERNAME
          server-password: GITHUB_TOKEN
      
      - name: Build and publish
        run: mvn deploy -DskipTests
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}